Repository hacknaman1/ACEIT, pull requests merged in 2022-10, with the labels that each got.

#3 script all saved passwords
  Python/wifipasswordscripter.py
Labels: hacktoberfest-accepted

#5 Depth-First Search algorithm
  DFS.cpp
Labels: good first issue, hacktoberfest-accepted

#6 created an binary search algo in c++
  binarysearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create responsivesite.html
  HTML/responsivesite.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#14 Create downward_triangle_pattern.py
  downward_triangle_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest
